import * as vscode from 'vscode';

export function getWebviewContent(panel: vscode.WebviewPanel): string {
	const toolkitUri = panel.webview.asWebviewUri(vscode.Uri.joinPath(
		vscode.Uri.file(__dirname),
		'..',
		'..',
		'..',
		'node_modules',
		'@vscode',
		'webview-ui-toolkit',
		'dist',
		'toolkit.js',
	));

	return [
		'<!DOCTYPE html>',
		'<html lang="en">',
		'<head>',
		'  <meta charset="UTF-8">',
		'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
		'  <title>FlowLens Sessions</title>',
		`  <script type="module" src="${toolkitUri}"></script>`,
		'  <style>',
		'    body { background: #0b1220; color: #fff; font-family: system-ui, Segoe UI, Roboto, Helvetica, Arial; margin: 0; padding: 0; }',
		'    .container { max-width: 600px; margin: 40px auto; background: #181c24; border-radius: 12px; box-shadow: 0 4px 32px #0004; padding: 32px 24px; }',
		'    h1 { font-size: 2rem; margin-bottom: 1.5rem; }',
		'    .search-bar { display: flex; align-items: center; margin-bottom: 1.5rem; gap: 0.5rem; }',
		'    .search-input { flex: 1; padding: 0.5rem 1rem; border-radius: 6px; border: 1px solid #23272e; background: #23272e; color: #fff; font-size: 1rem; outline: none; transition: border 0.2s; }',
		'    .search-input:focus { border: 1.5px solid #388bfd; background: #23272e; }',
		'    .session { background: #23272e; border-radius: 8px; margin-bottom: 1rem; padding: 1rem 1.5rem; display: flex; justify-content: space-between; align-items: flex-start; }',
		'    .session-info { flex: 1; }',
		'    .session-title { font-weight: 600; font-size: 1.1rem; }',
		'    .session-meta { color: #a0aec0; font-size: 0.95rem; margin-bottom: 0.5rem; }',
		'    .session-notes { color: #e0e7ef; font-size: 0.95rem; margin-bottom: 0.5rem; }',
		'    .session-workspace { color: #7dd3fc; font-size: 0.9rem; margin-bottom: 0.5rem; display: inline-flex; align-items: center; gap: 0.25rem; }',
		'    .session-actions { display: flex; flex-direction: column; gap: 0.5rem; min-width: 110px; }',
		'    .session-editors { color: #b5cdfa; font-size: 0.92rem; margin-top: 0.5rem; }',
		'    .empty { color: #7dd3fc; text-align: center; margin: 2rem 0; }',
		'    vscode-button, button {',
		'      font-size: 1rem;',
		'      border-radius: 6px;',
		'      padding: 0.45rem 1.1rem;',
		'      font-weight: 500;',
		'      margin: 0;',
		'      box-shadow: none;',
		'      transition: background 0.15s, color 0.15s, border 0.15s;',
		'    }',
		'    vscode-button[appearance="primary"] { background: #388bfd; color: #fff; border: none; }',
		'    vscode-button[appearance="primary"]:hover, vscode-button[appearance="primary"]:focus { background: #2563eb; color: #fff; }',
		'    vscode-button[appearance="secondary"] { background: #23272e; color: #b5cdfa; border: 1px solid #3b4252; }',
		'    vscode-button[appearance="secondary"]:hover, vscode-button[appearance="secondary"]:focus { background: #1e222a; color: #fff; border: 1.5px solid #388bfd; }',
		'  </style>',
		'</head>',
		'<body>',
		'  <div class="container">',
		'    <h1>FlowLens Sessions</h1>',
		'    <div class="search-bar">',
		'      <input id="search" class="search-input" type="text" placeholder="Search sessions, notes, files, terminals..." autocomplete="off" spellcheck="false" />',
		'    </div>',
		'    <div style="margin-bottom: 1rem;">',
		'      <label style="display: inline-flex; align-items: center; gap: 0.5rem; cursor: pointer; color: #a0aec0;">',
		'        <input type="checkbox" id="filterWorkspace" style="cursor: pointer;" />',
		'        <span id="filterLabel">Show current workspace only</span>',
		'      </label>',
		'    </div>',
		'    <div id="sessions"></div>',
		'    <div id="empty" class="empty" style="display:none">No sessions yet. Use <b>Capture Session</b> to save your context.</div>',
		'  </div>',
		'  <script type="module">',
		'    const vscode = acquireVsCodeApi();',
		'    let allSessions = [];',
		'    let currentWorkspace = null;',
		'    function escapeHtml(text) {',
		'      if (!text) return "";',
		'      const div = document.createElement("div");',
		'      div.textContent = text;',
		'      return div.innerHTML;',
		'    }',
		'    function applyFilters(query, workspaceFilter) {',
		'      let filtered = allSessions;',
		'',
		'      if (workspaceFilter && currentWorkspace) {',
		'        filtered = filtered.filter(s => s.workspace && s.workspace.path === currentWorkspace.path);',
		'      }',
		'',
		'      if (query) {',
		'        const q = query.toLowerCase();',
		'        filtered = filtered.filter(session => {',
		'          if ((session.title && session.title.toLowerCase().includes(q)) ||',
		'              (session.notes && session.notes.toLowerCase().includes(q)) ||',
		'              (session.workspace && session.workspace.name && session.workspace.name.toLowerCase().includes(q)) ||',
		'              (session.editors && session.editors.some(e => e.path && e.path.toLowerCase().includes(q))) ||',
		'              (session.terminals && session.terminals.some(t => (t.name && t.name.toLowerCase().includes(q)) || (t.lastCommand && t.lastCommand.toLowerCase().includes(q))))',
		'          ) return true;',
		'          return false;',
		'        });',
		'      }',
		'      return filtered;',
		'    }',
		'    function renderSessions(sessions) {',
		'      const root = document.getElementById("sessions");',
		'      root.innerHTML = "";',
		'      if (!sessions || sessions.length === 0) {',
		'        document.getElementById("empty").style.display = "";',
		'        return;',
		'      }',
		'      document.getElementById("empty").style.display = "none";',
		'      sessions.forEach(session => {',
		'        const div = document.createElement("div");',
		'        div.className = "session";',
		'        const workspaceBadge = session.workspace ',
		'          ? `<div class="session-workspace">📁 ${escapeHtml(session.workspace.name)}</div>`',
		'          : `<div class="session-workspace">📄 No workspace</div>`;',
		'        div.innerHTML = ',
		'          `<div class="session-info">` +',
		'            `<div class="session-title">${escapeHtml(session.title) || "Untitled"}</div>` +',
		'            `<div class="session-meta">${escapeHtml(new Date(session.timestamp).toLocaleString())}</div>` +',
		'            workspaceBadge +',
		'            (session.notes ? `<div class="session-notes">${escapeHtml(session.notes)}</div>` : "") +',
		'            `<div class="session-editors">${(session.editors||[]).map(e => `${escapeHtml(e.path)}${e.cursor ? ` (${e.cursor.line+1}:${e.cursor.col+1})` : ""}`).join("<br>")}</div>` +',
		'          `</div>` +',
		'          `<div class="session-actions">` +',
		'            `<vscode-button appearance="primary" data-id="${escapeHtml(session.id)}" data-action="resume">Resume</vscode-button>` +',
		'            `<vscode-button appearance="secondary" data-id="${escapeHtml(session.id)}" data-action="delete">Delete</vscode-button>` +',
		'          `</div>`;',
		'        root.appendChild(div);',
		'      });',
		'      root.querySelectorAll("vscode-button").forEach(btn => {',
		'        btn.addEventListener("click", e => {',
		'          const id = btn.getAttribute("data-id");',
		'          const action = btn.getAttribute("data-action");',
		'          vscode.postMessage({ type: action, id });',
		'        });',
		'      });',
		'    }',
		'    function refreshSessionList() {',
		'      const searchVal = document.getElementById("search").value;',
		'      const workspaceFilter = document.getElementById("filterWorkspace").checked;',
		'      const filtered = applyFilters(searchVal, workspaceFilter);',
		'      renderSessions(filtered);',
		'    }',
		'    window.addEventListener("message", event => {',
		'      if (event.data && event.data.type === "sessions") {',
		'        allSessions = event.data.data;',
		'        currentWorkspace = event.data.currentWorkspace;',
		'        ',
		'        if (currentWorkspace) {',
		'          document.getElementById("filterLabel").textContent = `Show ${currentWorkspace.name} only`;',
		'        }',
		'        refreshSessionList();',
		'      }',
		'      if (event.data && event.data.type === "deleted") {',
		'        allSessions = allSessions.filter(s => s.id !== event.data.id);',
		'        refreshSessionList();',
		'      }',
		'    });',
		'    document.getElementById("search").addEventListener("input", refreshSessionList);',
		'    document.getElementById("filterWorkspace").addEventListener("change", refreshSessionList);',
		'    vscode.postMessage({ type: "ready" });',
		'  </script>',
		'</body>',
		'</html>'
	].join('\n');
}
